### ISSUE TITLE
opencl support?

### ISSUE THREAD

**Issue by allthetime** [johnglover/sound-rnn#3]
Hey, do you know if anyone has got this working with opencl/amd cards?

I managed to get char-rnn/word-rnn working by [changing a single line](https://github.com/larspars/word-rnn/pull/11/commits/df4c23a7232493a2ebb26b2ebe0fff4753317795) that gets the program to use the proper tensor type. Do you think a similar fix might be possible?

I'm wondering if you could give me any insight to how and where CUDA is being used here and if you know of any way I might be able to replace it with opencl. I am a RNN/ML noob, so anything helps!

Thanks.

**Comment by johnglover** [comment]
Hey,

I have not heard of anyone working on this with opencl, and I have never used it myself so I'm not sure how much work it would be. If you want to know what changes were necessary to add CUDA support have a look at the PR that @jfsantos made: https://github.com/johnglover/sound-rnn/pull/1. Hope that helps.
